cnrancher/autok3s

- README.md
> docs(autok3s): add go-report & release badges

- README.md
> docs(autok3s): change badge color

- docs/alibaba/ram.md
> docs(alibaba): update RAMs

- README.md
> docs(autok3s): add demo video

- pkg/providers/alibaba/alibaba.go
- pkg/providers/alibaba/template.go
> fix(alibaba): fix ccm bugs

- pkg/providers/alibaba/alibaba.go
> fix(alibaba): fix delete error when pod associate with Terway ENI IP

- pkg/cluster/cluster.go
- pkg/providers/alibaba/alibaba.go
> feat(autok3s): add k3s command debug logs

- pkg/cluster/cluster.go
> feat(autok3s): wrap ssh command error

- pkg/providers/native/native.go
Signed-off-by: NewGr8Player <273221594@qq.com>
> fix(native): fix rollback error

- README_zhCN.md
- docs/alibaba/README.md
- docs/alibaba/README_zhCN.md
- docs/native/README.md
- docs/native/README_zhCN.md
- docs/tencent/README_zhCN.md
Signed-off-by: NewGr8Player <273221594@qq.com>
> docs(autok3s): add chinese docs

- README.md
- README_zhCN.md
> docs(autok3s): add chinese language

- README_zhCN.md
> docs(autok3s): format the document

- pkg/providers/alibaba/alibaba.go
- pkg/providers/native/native.go
- pkg/providers/tencent/tencent.go
> fix(autok3s): change k3s-channel to latest

- README.md
- README_zhCN.md
> docs(autok3s): update README.md

- cmd/cmd.go
- pkg/cli/kubectl/kubectl.go
> fix(kubectl): fix --cfg not working bug

- docs/i18n/en_us/native/README.md
- docs/i18n/zh_cn/native/README.md
> docs(native): fix typo

- pkg/providers/alibaba/alibaba.go
- pkg/providers/native/native.go
- pkg/providers/tencent/tencent.go
> fix(autok3s): change default k3s_channel to stable

- docs/i18n/en_us/alibaba/README.md
- docs/i18n/en_us/native/README.md
- docs/i18n/en_us/tencent/README.md
- docs/i18n/zh_cn/alibaba/README.md
- docs/i18n/zh_cn/native/README.md
- docs/i18n/zh_cn/tencent/README.md
> docs(autok3s): format README.md

- cmd/create.go
- cmd/join.go
- docs/i18n/en_us/tencent/README.md
- docs/i18n/zh_cn/tencent/README.md
- pkg/providers/alibaba/alibaba.go
- pkg/providers/native/native.go
- pkg/providers/tencent/tencent.go
https://github.com/cnrancher/autok3s/issues/166
> fix(autok3s): set ssh default user and ssh key path in different provider

- cmd/create.go
- cmd/delete.go
- cmd/join.go
- cmd/ssh.go
- cmd/start.go
- cmd/stop.go
- pkg/providers/alibaba/flag.go
- pkg/providers/native/flag.go
- pkg/providers/provider.go
- pkg/providers/tencent/flag.go
> fix(autok3s): dynamically show the usage info

- README.md
- docs/i18n/zh_cn/README.md
> docs(autok3s): add contents for README.md

- pkg/cluster/cluster.go
- pkg/providers/alibaba/alibaba.go
- pkg/providers/alibaba/flag.go
- pkg/providers/native/flag.go
- pkg/providers/native/native.go
- pkg/providers/tencent/flag.go
- pkg/providers/tencent/tencent.go
- pkg/types/autok3s.go
> feat(autok3s): add --k3s-install-script flag

- pkg/cluster/cluster.go
- pkg/hosts/tunnel.go
> feat(autok3s): use multi-writer when execute ssh-cmd

- pkg/cluster/cluster.go
> fix(autok3s): fix empty cfg file

- pkg/providers/alibaba/alibaba.go
- pkg/providers/tencent/tencent.go
> style(autok3s): change random-pass log

- pkg/providers/alibaba/alibaba.go
- pkg/providers/tencent/tencent.go
> style(autok3s): remove useless code

- pkg/cluster/cluster.go
- pkg/providers/native/native.go
#169 
fix native
- show warn message in Delete and RollBack if failed to execute uninstall k3s command
> fix(native): show log when execute uninstall k3s

- pkg/cluster/cluster.go
- pkg/providers/alibaba/alibaba.go
- pkg/providers/native/native.go
- pkg/providers/provider.go
- pkg/providers/tencent/tencent.go
#191   
1. check cluster exist
2. sync .state when finish delete the cluster
> fix(native): fix delete native provider's cluster

- pkg/providers/native/native.go
> fix(native): check to see if the cluster exists

- cmd/cmd.go
- cmd/common/common.go
- cmd/describe.go
- cmd/list.go
- go.mod
- main.go
- pkg/cluster/cluster.go
- pkg/providers/alibaba/alibaba.go
- pkg/providers/native/native.go
- pkg/providers/provider.go
- pkg/providers/tencent/tencent.go
- pkg/types/autok3s.go
- refactor list command: check k3s status by kubeconfig (https://github.com/cnrancher/autok3s/issues/168)
- add describe command: show detail nodes information of cluster(https://github.com/cnrancher/autok3s/issues/83)
- set external-ip for k3s nodes
> feat(autok3s): add support for describe cluster command

- cmd/common/common.go
- cmd/describe.go
- docs/i18n/en_us/alibaba/README.md
- docs/i18n/en_us/native/README.md
- docs/i18n/en_us/tencent/README.md
- docs/i18n/zh_cn/alibaba/README.md
- docs/i18n/zh_cn/native/README.md
- docs/i18n/zh_cn/tencent/README.md
- pkg/cluster/cluster.go
- pkg/providers/alibaba/flag.go
- pkg/providers/native/flag.go
- pkg/providers/native/native.go
- pkg/providers/tencent/flag.go
> refactor(native): change native provider logic

- pkg/providers/alibaba/alibaba.go
- pkg/providers/tencent/tencent.go
- fix query instances and eips by page(https://github.com/cnrancher/autok3s/issues/176)
- fix setting internet bandwidth for alibaba provider(https://github.com/cnrancher/autok3s/issues/204)
- fix create check logic for setting `--zone` if using specified `--region`(https://github.com/cnrancher/autok3s/issues/203)
> fix(autok3s): fix query instance and eips by page

- cmd/create.go
- cmd/describe.go
- cmd/list.go
- docs/i18n/en_us/alibaba/README.md
- docs/i18n/en_us/tencent/README.md
- docs/i18n/zh_cn/alibaba/README.md
- docs/i18n/zh_cn/tencent/README.md
- pkg/cluster/cluster.go
- pkg/providers/alibaba/alibaba.go
- pkg/providers/alibaba/flag.go
- pkg/providers/native/native.go
- pkg/providers/provider.go
- pkg/providers/tencent/flag.go
- pkg/providers/tencent/tencent.go
- pkg/types/autok3s.go
- add short hand `-n` flag for `--name`
- add `-p` and `--region` param for describe command
- remove `<.region>` for list and describe result
- add `.<provider>` for kubeconfig context
> fix(autok3s): add param for describe command

- pkg/cluster/cluster.go
https://github.com/cnrancher/autok3s/issues/162#issuecomment-751998068
> fix(autok3s): fix upload registry file without tls config

- docs/i18n/en_us/alibaba/README.md
- docs/i18n/en_us/native/README.md
- docs/i18n/en_us/tencent/README.md
- docs/i18n/zh_cn/alibaba/README.md
- docs/i18n/zh_cn/native/README.md
- docs/i18n/zh_cn/tencent/README.md
- pkg/cluster/cluster.go
- pkg/cluster/template.go
- pkg/providers/alibaba/alibaba.go
- pkg/providers/alibaba/flag.go
- pkg/providers/native/flag.go
- pkg/providers/native/native.go
- pkg/providers/tencent/flag.go
- pkg/providers/tencent/tencent.go
- pkg/types/autok3s.go
- Add `--cluster` param for create command to install HA cluster using embedded DB(https://github.com/cnrancher/autok3s/issues/208)
- Deploy latest dashboard for `--ui`(https://github.com/cnrancher/autok3s/issues/211)
> fix(autok3s): add param for create command to install HA cluster using embedded DB

- pkg/providers/tencent/tencent.go
https://github.com/cnrancher/autok3s/issues/214
> fix(autok3s): change system disk default size of tencent provider

- docs/i18n/en_us/alibaba/README.md
- docs/i18n/en_us/aws/README.md
- docs/i18n/zh_cn/alibaba/README.md
- docs/i18n/zh_cn/aws/README.md
- pkg/server/store/websocket/kubectl.go
- pkg/server/store/websocket/kubectl_windows.go
- fix kubectl websocket for windows build
- fix alibaba/aws README for RAM/IAM permission
> fix(autok3s): fix kubectl websocket for windows build

- README.md
- docs/i18n/zh_cn/README.md
this pull request contains the following changes in Chinese and English readme docs:
1. Changes in "Frequently-used Parameters": charts are changed to unordered lists (or bullet points) to avoid unusual display on cell phone sceen.
2. Changes the orders of some sections to make more sense and to read more smoothly.
> docs(autok3s): refactor readme docs

- hack/make-rules/autok3s.sh
- pkg/cluster/cluster.go
- pkg/providers/alibaba/alibaba.go
- pkg/providers/aws/aws.go
- pkg/providers/native/native.go
- pkg/providers/tencent/tencent.go
- pkg/server/store/cluster/action.go
- pkg/server/store/cluster/store.go
- pkg/server/store/websocket/log.go
- pkg/types/autok3s.go
- update UI version
- save failed cluster options, allow user back to edit options from UI
> fix(autok3s): allow edit failed cluster for UI

- README.md
- docs/i18n/en_us/alibaba/README.md
- docs/i18n/zh_cn/README.md
- docs/i18n/zh_cn/alibaba/README.md
- delete redundant description on README.md, in CN and EN.
- add "简体中文/English" tags in the beginning of alibaba CN and EN docs.
- refactor alibaba CN and EN docs.
> docs(autok3s): update alibaba CN and EN

- docs/i18n/en_us/alibaba/README.md
- docs/i18n/en_us/aws/README.md
- docs/i18n/en_us/native/README.md
- docs/i18n/en_us/tencent/README.md
- docs/i18n/zh_cn/alibaba/README.md
- docs/i18n/zh_cn/aws/README.md
- docs/i18n/zh_cn/native/README.md
- docs/i18n/zh_cn/tencent/README.md
> docs(autok3s): update and refactor all docs

- README.md
- docs/i18n/en_us/alibaba/README.md
- docs/i18n/en_us/aws/README.md
- docs/i18n/en_us/native/README.md
- docs/i18n/en_us/tencent/README.md
- docs/i18n/zh_cn/README.md
- docs/i18n/zh_cn/alibaba/README.md
- docs/i18n/zh_cn/aws/README.md
- docs/i18n/zh_cn/native/README.md
- docs/i18n/zh_cn/tencent/README.md
fix typos and replace them with some more appropriate words/phrases.
> docs(autok3s): fix typos

- pkg/providers/alibaba/alibaba.go
- pkg/providers/alibaba/flag.go
- pkg/providers/aws/aws.go
- pkg/providers/aws/flag.go
- pkg/providers/tencent/flag.go
- pkg/providers/tencent/tencent.go
- pkg/types/alibaba/alibaba.go
- pkg/types/aws/aws.go
- pkg/types/tencent/tencent.go
- pkg/utils/flag.go
> feat(autok3s): add --tags flag

- Dockerfile.dapper
- hack/make-rules/autok3s.sh
> fix(autok3s): fix cross-build problem

- hack/lib/constant.sh
- hack/make-rules/autok3s.sh
> fix(autok3s): cross-build for Darwin is not supported

- Dockerfile
- Dockerfile.dapper
> fix(image): fix env value and set default cmd

- Dockerfile
- hack/lib/docker.sh
- hack/make-rules/autok3s.sh
- pkg/server/store/websocket/kubectl/kubectl.go
- support auto-completion for kubectl command
- support alias k for short kubectl
https://github.com/cnrancher/autok3s/issues/265
> feat(image): Support bash completion for the kubectl command

- .drone.yml
> style(drone): change ci pipeline

- pkg/common/common.go
- pkg/hosts/dialer.go
- pkg/providers/aws/aws.go
- pkg/providers/utils/utils.go
- pkg/utils/keys.go
> fix(aws): automatic key pair generation needs to be atomic

- Dockerfile
https://github.com/cnrancher/autok3s/issues/288
> fix(image): Support upgrading for container mode

- pkg/cluster/base.go
- pkg/cluster/cluster.go
- pkg/providers/alibaba/alibaba.go
- pkg/providers/aws/aws.go
- pkg/providers/native/flag.go
- pkg/providers/native/native.go
- pkg/providers/tencent/tencent.go
- pkg/types/autok3s.go
- allow set k3s-install-script from UI (https://github.com/cnrancher/autok3s/issues/294)
- refactor rollback logic for provider
- remove UI manifest if enabled CCM when delete cluster
> fix(provider): refactor rollback logic

- scritps/install.sh
The auto-sync script will sync this install script to the CN mirror every day.
> feat(script): add install script

- README.md
- docs/i18n/en_us/alibaba/README.md
- docs/i18n/en_us/aws/README.md
- docs/i18n/en_us/k3d/README.md
- docs/i18n/en_us/native/README.md
- docs/i18n/en_us/tencent/README.md
1. add k3d provider docs.
2. fix docs typo.
> docs(k3d): add k3d provider docs

- README.md
- hack/make-rules/autok3s.sh
- pkg/providers/k3d/flag.go
- pkg/providers/k3d/k3d.go
> fix(k3d): fix options bug

- pkg/server/server.go
- pkg/server/ui/ui.go
- Using remote ui-index when set environment `AUTOK3S_UI_MODE = dev`
- Using custom ui-index url when set environment `AUTOK3S_UI_INDEX` value
> feat(ui): support dev ui

- pkg/cluster/base.go
- pkg/cluster/cluster.go
https://github.com/cnrancher/autok3s/issues/319
> fix(docker): check docker before running install command

- Dockerfile
- go.mod
- pkg/cluster/base.go
- pkg/providers/k3d/flag.go
- pkg/providers/native/native.go
- Add deploy manifest yaml for native provider(https://github.com/cnrancher/autok3s/issues/326)
- Add curl to docker image
- remove repeat flag for k3d provider
> fix(native): support --manifest for native provider

- Dockerfile
- pkg/providers/native/native.go
https://github.com/cnrancher/autok3s/issues/332
> fix(native): fix get user home directory for native provider

- README.md
> docs(autok3s): add badge link

- README.md
update quick start
Signed-off-by: ysicing <i@ysicing.me>
> docs(version): update quick start

- go.mod
- go.sum
> feat(k3d): bump k3d to v4.4.8

- Dockerfile
- Dockerfile.dapper
- hack/make-rules/autok3s.sh
- scripts/install.sh
https://github.com/cnrancher/autok3s/issues/351
> fix(kube-explorer): bump up kube-explorer version

- .gitignore
- cmd/cmd.go
- go.mod
- go.sum
- hack/make-rules/autok3s.sh
- pkg/providers/alibaba/alibaba.go
- pkg/providers/aws/aws.go
- pkg/providers/google/flag.go
- pkg/providers/google/google.go
- pkg/providers/native/native.go
- pkg/providers/tencent/tencent.go
- pkg/server/store/cluster/store.go
- pkg/types/google/google.go
https://github.com/cnrancher/autok3s/issues/306
> feat(provider): support gce provider

- Dockerfile
- Dockerfile.dapper
- hack/make-rules/autok3s.sh
- scripts/install.sh
This reverts commit 1d240183d04241a9c08dee7d899d211a636ec8a9.
> fix(kube-explorer): revert bump up kube-explorer version

- cmd/list.go
for scripting purposes the json output is better than the table format.
> add option to produce json list

- README.md
> docs(autok3s): add source-code subject

- Dockerfile
- scripts/install.sh
> feat(kube-explorer): bump up kube-explorer version

- docs/i18n/en_us/google/README.md
- pkg/providers/alibaba/alibaba.go
- pkg/providers/aws/aws.go
- pkg/providers/google/flag.go
- pkg/providers/google/google.go
- pkg/providers/google/template.go
- pkg/providers/tencent/tencent.go
https://github.com/cnrancher/autok3s/issues/350
> feat(google): support gcp cloud provider

- Dockerfile
- cmd/cmd.go
- cmd/describe.go
- go.mod
- go.sum
- pkg/cluster/base.go
- pkg/cluster/cluster.go
- pkg/common/common.go
- pkg/common/explorer.go
- pkg/common/file.go
- pkg/server/store/cluster/action.go
- pkg/server/store/kubectl/store.go
- scripts/install.sh
https://github.com/cnrancher/autok3s/issues/378
- fix merge kubeconfig locked file problem for windows
- bump up kube-explorer version
There's difference between linux and windows when setting KUBECONFIG env [here](https://kubernetes.io/docs/tasks/access-application-cluster/configure-access-multiple-clusters/#linux-1)
> fix merge kubeconfig locked file problem for windows

- hack/make-rules/autok3s.sh
- pkg/providers/google/google.go
- pkg/types/tencent/tencent.go
https://github.com/cnrancher/autok3s/issues/387
> fix(provider): fix google vm name and tencent flag name

- go.mod
- go.sum
> fix(autok3s): go mod tidy

- pkg/providers/native/flag.go
- pkg/providers/native/native.go
https://github.com/cnrancher/autok3s/issues/391
> fix(native): fix default --ssh-password problem

- pkg/types/harvester/harvester.go
https://github.com/cnrancher/autok3s/issues/269
> fix(harvester): fix harvester options typo

- pkg/common/common.go
- pkg/hosts/ssh.go
https://github.com/cnrancher/autok3s/issues/408
> fix(ssh): change ssh default connect timeout parameter

- pkg/providers/harvester/cloudinit.go
https://github.com/cnrancher/autok3s/issues/413
> fix(harvester): fix saving user-data/network-data to cloud config secret

- pkg/cluster/base.go
- pkg/providers/native/flag.go
- pkg/providers/native/native.go
https://github.com/cnrancher/autok3s/issues/410
> fix(native): fix join multiple nodes for native provider

- pkg/cluster/base.go
- pkg/common/common.go
https://github.com/cnrancher/autok3s/issues/409
> feat(cluster): add removing status for cluster

- cmd/list.go
- docs/i18n/en_us/native/README.md
- go.mod
- go.sum
- hack/make-rules/autok3s.sh
- pkg/cluster/base.go
- pkg/cluster/cluster.go
- pkg/common/db.go
- pkg/common/model.go
- pkg/providers/alibaba/flag.go
- pkg/providers/aws/flag.go
- pkg/providers/google/flag.go
- pkg/providers/harvester/flag.go
- pkg/providers/k3d/flag.go
- pkg/providers/native/flag.go
- pkg/providers/native/native.go
- pkg/providers/tencent/flag.go
- pkg/server/store/cluster/store.go
- pkg/types/autok3s.go
https://github.com/cnrancher/autok3s/issues/407
> feat(native): support join nodes for existing cluster that is not hanlded by AutoK3s

- README.md
- go.mod
- go.sum
- hack/lib/install.sh
- pkg/cluster/cluster.go
- pkg/providers/alibaba/alibaba.go
- pkg/providers/tencent/tencent.go
- scripts/install.sh
https://github.com/cnrancher/autok3s/issues/427
> fix(autok3s): update mirror url for CN

- pkg/providers/tencent/flag.go
- pkg/providers/tencent/tencent.go
- pkg/types/tencent/tencent.go
> 在创建云服务器时，您可以通过指定自定义数据，进行配置实例。当云服务器首次启动时，自定义数据将以文本的方式传递到云服务器中，并执行该文本。如果您一次购买多台云服务器，自定义数据会在所有的云服务器首次启动时运行该文本。
> https://cloud.tencent.com/document/product/213/17525
> https://cloud.tencent.com/document/product/213/15730
Easy for us to initialize the system.
> feat(tencent): Support UserData for tencent provider

- pkg/server/server.go
- pkg/server/ui/ui.go
https://github.com/cnrancher/autok3s/issues/426
> fix(ui): support ui MIME issue on Windows

- pkg/server/schema.go
- pkg/server/store/cluster/action.go
- pkg/types/apis/types.go
Refactor cluster action handler
https://github.com/cnrancher/autok3s/issues/420
> feat(autok3s): add download kubeconfig API

- go.mod
- go.sum
- hack/make-rules/autok3s.sh
- pkg/common/db.go
- pkg/common/model.go
- pkg/providers/harvester/client.go
- pkg/providers/harvester/cloudinit.go
- pkg/providers/harvester/harvester.go
- pkg/server/proxy/http_proxy.go
- pkg/server/proxy/k8s_proxy.go
- pkg/server/schema.go
- pkg/server/server.go
- pkg/server/store/settings/store.go
- pkg/utils/util.go
https://github.com/cnrancher/autok3s/issues/412
> feat(autok3s): add proxy for UI

- scripts/install.sh
https://github.com/cnrancher/autok3s/issues/430
> fix(autok3s): fix uninstall scripts

- pkg/providers/alibaba/alibaba.go
- pkg/providers/alibaba/flag.go
- pkg/providers/tencent/flag.go
- pkg/providers/tencent/tencent.go
- pkg/types/alibaba/alibaba.go
- pkg/types/tencent/tencent.go
https://github.com/cnrancher/autok3s/issues/452
> feat(provider): add spot instance support for alibaba/tencent provider

- pkg/providers/google/flag.go
- pkg/providers/google/google.go
- pkg/types/google/google.go
https://github.com/cnrancher/autok3s/issues/449
> feat(google): support startup-script for google provider

- .drone.yml
- hack/make-rules/release-note.sh
Replace release note generator and github release image with official
image. Now using aevea/release-notary:0.9.2 and plugins/github-release.
> fix(ci)Replace with official image

- hack/lib/upx.sh
> fix(ci): Set compress rate to 5

- .drone.yml
Related issue: https://github.com/aevea/commitsar/issues/354
Skip commisar check when pushing master.
> fix(ci): commisar doesn't work with merge commit

- pkg/cluster/dashboard_template.go
> feat(dashboard): bump to kubernetes/dashboard to 2.6.0

- docs/i18n/en_us/alibaba/README.md
- docs/i18n/en_us/aws/README.md
- docs/i18n/en_us/google/README.md
- docs/i18n/en_us/harvester/README.md
- docs/i18n/en_us/native/README.md
- docs/i18n/en_us/tencent/README.md
- go.mod
Related issue: https://github.com/cnrancher/autok3s/issues/471
> Remove dashboard in readme

- pkg/providers/google/template.go
> feat(google): bump google ccm to 4.12.0

- cmd/cmd.go
- cmd/telemetry.go
- pkg/common/db.go
- pkg/common/metrics.go
- pkg/common/setting_provider.go
- pkg/common/uuid.go
- pkg/settings/setting.go
Using a seperated settings package and init settings from it.
> feat(autok3s): Refactor setting design

- pkg/providers/alibaba/alibaba.go
- pkg/providers/alibaba/template.go
> feat(alibaba): bump alibaba ccm to 2.4.0

- pkg/providers/alibaba/alibaba.go
- pkg/providers/tencent/tencent.go
> feat(autok3s): temporary change k3sInstallScript to working address

- hack/make-rules/autok3s.sh
> feat(ui): bump ui version to v0.5.2-rc2

- hack/make-rules/autok3s.sh
> feat(ui): bump ui version to v0.5.2-rc3

- scripts/install.sh
Refer to issue: https://github.com/cnrancher/autok3s/issues/484
> fix(autok3s): fix break link in install script

- cmd/airgap/args.go
- go.mod
- go.sum
- pkg/airgap/download.go
- pkg/airgap/tarfiles.go
- pkg/common/db.go
- pkg/common/model.go
- pkg/common/package.go
- pkg/server/schema.go
- pkg/server/server.go
- pkg/server/store/cluster/store.go
- pkg/server/store/explorer/store.go
- pkg/server/store/pkg/schema.go
- pkg/server/store/pkg/store.go
- pkg/server/store/settings/store.go
- pkg/server/store/template/store.go
- pkg/types/apis/types.go
- pkg/types/autok3s.go
Related issue: https://github.com/cnrancher/autok3s/issues/448
The airgap API function is under /v1/pacakges and supports:
- create
- update
- remove
- list/get
- import
- export
- update install script
> feat(autok3s): support airgap API function

- Dockerfile
- scripts/install.sh
v0.2.10 can work well with k8s 1.24.
> feat(dashboard): Bump kube-explorer v0.2.10

- pkg/cluster/commands.go
- pkg/cluster/commands_test.go
Related issue: https://github.com/cnrancher/autok3s/issues/388
> fix(auto3s): Use internal ip as advertise address

- pkg/server/schema.go
- pkg/server/store/credential/schema.go
#263 
URL | Method | Url.Values
-----|---------|-----------
`/v1/credentials/{id}?link=zone`| GET | project=xxx |
`/v1/credentials/{id}?link=region`| GET | project=xxx |
`/v1/credentials/{id}?link=machineType`| GET | project=xxx&zone=xxx |
`/v1/credentials/{id}?link=machineImage`| GET | project=xxx |
`/v1/credentials/{id}?link=diskType`| GET | project=xxx&zone=xxx |
`/v1/credentials/{id}?link=network`| GET | project=xxx |
> feat(credential): add google api for ui-forms

- Dockerfile
- scripts/install.sh
What's new about kube-explorer v0.2.12?
https://github.com/cnrancher/kube-explorer/releases/tag/v0.2.12
> feat(dashboard): Bump kube-explorer v0.2.12

- README.md
- docs/i18n/en_us/airgap/README.md
Refer to issue https://github.com/cnrancher/autok3s/issues/448
> docs(autok3s): Add airgap install docs

- README.md
- docker-compose.yaml
- hack/make-rules/autok3s.sh
> feat(autok3s): bump to v0.6.0

- docker-compose.yaml
> fix(docker-compose): fix docker-compose mount path error

- Dockerfile
- scripts/install.sh
https://github.com/cnrancher/autok3s/issues/527
> feat(dashboard): Bump kube-explorer v0.2.13

- pkg/airgap/file_scp.go
Refer to https://github.com/cnrancher/autok3s/issues/549
> fix(airgap): fix parse wrong arch

- pkg/providers/alibaba/alibaba.go
- pkg/providers/aws/aws.go
- pkg/providers/tencent/tencent.go
Refer to following issues:
- https://github.com/cnrancher/autok3s/issues/497#issuecomment-1376650148
- https://github.com/cnrancher/pandaria-test-plan/issues/252#issuecomment-1376759069
> Fix v0.7.0-rc2 bugs

- go.mod
- go.sum
- pkg/cluster/base.go
- pkg/providers/alibaba/alibaba.go
- pkg/providers/aws/aws.go
- pkg/providers/google/google.go
- pkg/providers/k3d/k3d.go
- pkg/providers/native/native.go
- pkg/providers/tencent/tencent.go
- pkg/utils/file.go
- https://github.com/cnrancher/autok3s/issues/536
- bump up containerd version for go.mod to fix security alert.
> feat(provider): refactor create/join check args

- pkg/providers/native/native.go
- pkg/server/store/template/store.go
- pkg/types/apis/types.go
https://github.com/cnrancher/autok3s/issues/518
> feat(template): add HA mode and Datastore type for cluster template

- pkg/airgap/file_scp.go
- pkg/airgap/file_scp_test.go
- pkg/cluster/cluster.go
Related issue: https://github.com/cnrancher/autok3s/issues/578
> feat(airgap): Support scp files to node's data-dir

- cmd/airgap/create.go
- cmd/airgap/update.go
- pkg/airgap/download.go
- pkg/airgap/utils.go
- pkg/common/explorer.go
- pkg/common/log.go
- pkg/common/package.go
- pkg/server/schema.go
- pkg/server/store/pkg/schema.go
- pkg/server/store/pkg/store.go
- pkg/server/store/sshkey/schema.go
- pkg/server/store/websocket/log.go
Add following features:
- Add `Validating`, `Downloading` and `Verifying` state for airgap package
- Support display logs for airgap package downloading
Refer to issue: https://github.com/cnrancher/autok3s/issues/532
> Enhance airgap package function

- pkg/common/default_template.go
- pkg/providers/alibaba/alibaba.go
- pkg/providers/aws/aws.go
- pkg/providers/google/google.go
- pkg/providers/tencent/tencent.go
https://github.com/cnrancher/autok3s/issues/268
Will update `default_template` for all providers for each release.
> feat(provider): add quick-start template for provider

- pkg/cluster/base.go
- pkg/common/model.go
- pkg/server/schema.go
- pkg/server/store/pkg/schema.go
- pkg/server/store/pkg/store.go
- pkg/server/store/websocket/log.go
Related to feature: https://github.com/cnrancher/autok3s/issues/532
And Have minor fixes for log schema
> Fix download won't show problem

- cmd/serve.go
- go.mod
- go.sum
Related issue: https://github.com/cnrancher/autok3s/issues/340
> [REF]Open browser after serve UI

- hack/make-rules/autok3s.sh
- pkg/cluster/base.go
- pkg/cluster/commands.go
- pkg/providers/alibaba/alibaba.go
- pkg/providers/aws/aws.go
- pkg/providers/tencent/tencent.go
- remove useless deploy ui command
- fix validate ssh key function typo
- bump up ui version
> fix(provider): fix function typo and remove useless variable

- Dockerfile
- scripts/install.sh
refer to: https://github.com/cnrancher/kube-explorer/releases/tag/v0.3.2
> feat(dashboard): Bump kube-explorer v0.3.2

- cmd/dashboard.go
- cmd/serve.go
- main.go
- pkg/common/common.go
- pkg/common/dashboard.go
- pkg/common/explorer.go
- pkg/server/proxy/http_proxy.go
- pkg/server/store/settings/store.go
- pkg/settings/setting.go
https://github.com/cnrancher/autok3s/issues/499
> Support helm-dashboard plugin

- hack/lib/upx.sh
Refer to issue: https://github.com/cnrancher/autok3s/issues/619
> fix(build): skip upx darwin binaries

- pkg/cluster/base.go
- pkg/types/autok3s.go
https://github.com/cnrancher/autok3s/issues/504
> feat(provider): support non-rollback parameter when create/join node failed

- pkg/cluster/base.go
- pkg/types/autok3s.go
- pkg/utils/util.go
refer to: https://github.com/cnrancher/autok3s/pull/622
> fix(cluster): fix cannot merge bool type with false as zero value

- pkg/cluster/base.go
- pkg/cluster/cluster.go
- pkg/providers/native/flag.go
- pkg/providers/native/native.go
https://github.com/cnrancher/autok3s/issues/650
> feat(cluster): support partial rollback when creating clusters or joining nodes

- pkg/common/default_template.go
change default template for aws/alibaba/tencent providers
> feat(provider): bump up default template of providers

- pkg/cluster/base.go
> fix(k3d): fix HA mode pre-check error

- pkg/cluster/base.go
- pkg/cluster/cluster.go
- pkg/providers/aws/aws.go
https://github.com/cnrancher/autok3s/issues/677
> fix(aws): support v1.27 and newer cloud controller manager for aws provider

- pkg/cluster/base.go
- pkg/cluster/cluster.go
- pkg/server/store/provider/store.go
- pkg/types/autok3s.go
https://github.com/cnrancher/autok3s/issues/639
> feat(cluster): support customize config file for K3s server and agent
