cnrancher/autok3s

docs/i18n/en_us/aws/README.md, docs/i18n/zh_cn/README.md
修改了readme主页和aws页面的一些描述：
- amazone --- 拼写错了，应该改为 amazon或 aws，昨天跟超姐讨论之后决定改为 aws。代码里面的变量名称估计也需要改 @JacieChao
- ”关键特性“这一栏描述的东西其实是糅杂了2~3个不同的内容：功能/关键特性、常用命令和参数。所以我将”关键特性“分成了三个章节描述：关键特性、常用命令和常用参数。 @Jason-ZW @JacieChao jacie如果还有其他没列出来的命令或参数，请补充上去。
- 完善了”示例“章节
相关PR：
- https://github.com/cnrancher/autok3s/pull/223
- https://github.com/cnrancher/autok3s/pull/222
=> docs(autok3s): update docs

README.md, docker-compose.yaml
This docker-compose makes the following available"
- option for adding [basic auth](https://github.com/nginx-proxy/nginx-proxy#basic-authentication-support)
- cli and container uses the same `AUTOK3S_CONFIG` dir
- local server is available at: http://autok3s.vcap.me (mac/windows/linux)
=> add docker-compose.yaml

pkg/utils/flag.go
I was trying to execute the "Generate CLI Command" from the Cluster/Create dialog, but got this error message:
```
$ autok3s create --name test --master 1 --provider google  --disk-size 1 ...
Error: unknown flag: --disk-size 
```
=> fix(provider): convert int flags

pkg/providers/google/google.go
The google instance and the firewall rule is getting created, but the instance is missing the network tag, so the firewall rule is not effective.
=> fix(provider): add correct tag to gcp instance

Dockerfile, scripts/install.sh
This version can display the name matching the `--context` parameter, instead of the hardcoded `Local`.
```
./kube-explorer --context=default .....
```
=> feat(kube-explorer): bump up kube-explorer v0.2.8

pkg/cluster/base.go, pkg/cluster/cluster.go, pkg/types/autok3s.go
Support docker offline install  for private cloud which can't connect network.
=> support docker offline install

.gitignore, cmd/cmd.go, cmd/telemetry.go, go.mod, go.sum, main.go, pkg/cluster/base.go, pkg/cluster/cluster.go, pkg/cluster/types.go, pkg/common/db.go, pkg/common/log.go, pkg/common/metrics.go, pkg/common/model.go, pkg/common/uuid.go, pkg/metrics/metrics.go, pkg/server/server.go, pkg/utils/file.go, pkg/utils/util.go
1. The cluster/template group by provider and k3s version will be collected
as prometheus metrics.
2. Users will be asked if they would like to share metrics or not.
3. Metrics will be sent to https://telemetry.rancher.cn/ with user's permission.
4. Adding telemetry CLI command to show/set telemetry status.
5. Minor fixes.
=> Replace geoip support

pkg/metrics/metrics.go
Not showing error body if failed to push metrics.
=> fix(autok3s): ignore metrics push error

go.mod, go.sum, pkg/cluster/base.go, pkg/common/model.go, pkg/providers/aws/aws.go, pkg/providers/aws/template_test.go
The AWS CCM requires being upgraded after the cluster is upgraded.
So we support deploy compatible CCM version for different k3s version.
Related issue: https://github.com/cnrancher/autok3s/issues/463
=> feat(aws): Support AWS CCM with multiple version

pkg/common/db.go
The serve command will failed if autok3s is upgrading from 0.5.2. The root cause is from sqlite driver and gorm and we can't fix for now. So we just don't migrate credentials table for now and will have a better upgrade solution in later version.
=> Fix credential table create problem

pkg/common/db.go
Already tested with newly install autok3s and upgraded from v0.5.2. The credential function is ok in both case.
=> fix(autok3s): FIx credential table not created

pkg/utils/file.go
Should use `path/filepath` library to get the dir of file.
Refer to issue: https://github.com/cnrancher/autok3s/issues/520
=> fix(autok3s): fix break windows filepath problem

Dockerfile, docker-compose.yaml
This PR to solve the problem in the usage scenario in #524, adding the `DOCKER_HOST` environment variable to customize the `docker.sock` path
=> fix(env): Add DOCKER_HOST env

pkg/utils/file.go
Keep the old way as the worst case and get home dir from `os/user`
=> fix(autok3s): Get UserHome from os/user

Dockerfile, scripts/install.sh
refer to: https://github.com/cnrancher/kube-explorer/releases/tag/v0.3.0
I also checked k3s v1.25.x and v1.26.x. They seem to work fine.
However, strictly speaking, there is only good compatibility with 1.23.x and 1.24.x.
=> feat(dashboard): Bump kube-explorer v0.3.0

cmd/describe.go, pkg/cluster/base.go, pkg/server/store/template/store.go
Add skip `harvester` for List/Describe/List template situation to avoid provider register error for user historical data.
Will remove the check after harvester provider added back.
=> feat(provider): skip harvester provider check for historical data

pkg/providers/alibaba/alibaba.go, pkg/providers/aws/aws.go, pkg/providers/tencent/tencent.go
Return error when the ssh key path and the ssh key name are both empty.
=> fix(autok3s): Fix ssh key create check logic

pkg/cluster/base.go, pkg/providers/alibaba/alibaba.go, pkg/providers/aws/aws.go, pkg/providers/tencent/tencent.go
Different error message will be returned when running as CLI or UI mode.
Refer to comment https://github.com/cnrancher/autok3s/issues/497#issuecomment-1378154176
=> fix(autok3s): Validate empty ssh key input from API

pkg/providers/alibaba/alibaba.go
https://github.com/cnrancher/pandaria-test-plan/issues/252#issuecomment-1379847239
The `ssh.SSHPassword` is shared for all instances, if set empty after the first node upload keypair, other nodes will return SSH connect error which causes this issue.
=> fix(alibaba): Fix failed to upload keypair when creating cluster with multiple nodes

pkg/providers/alibaba/alibaba.go, pkg/providers/aws/aws.go, pkg/providers/aws/template.go, pkg/providers/aws/template_test.go, pkg/providers/google/google.go, pkg/providers/k3d/flag.go, pkg/providers/tencent/tencent.go
- Using `--disable` instead of `--no-deploy` cause v1.25.x has droped the parameter
- Fix K3sVersion empty error.If user deploy stable/latest version of K3s, this parameter will be empty and ccm manifest won't be deployed
https://github.com/cnrancher/pandaria-test-plan/issues/252#issuecomment-1379841307
=> fix(provider): fix failed to deploy ccm for K3s v1.25.x

pkg/cluster/base.go, pkg/providers/k3d/k3d.go
This PR fix the issue #615 
1. Clear the context config only when the cluster is not running.
2. After creating the k3d cluster, set `node.Rollback` to true, this will enable automatic rollback of the k3d cluster in case of any errors.
3. Fix the logic for generating k3d node name
=> fix(provider): update join k3d function and rollback logic

cmd/addon/args.go, cmd/addon/create.go, cmd/addon/get.go, cmd/addon/ls.go, cmd/addon/update.go, pkg/common/manifest.go, pkg/server/store/addon/store.go
- Remove --manifest args for create/update in cli as it's not useful.
- Add --unset args for update command to delete values of add-on.
- Add shortcut -f for --from args.
- The list command won't return manifest count.
- The get command will return the yaml format of addon.
=> fix(add-ons): minor addon CLI changes

hack/make-rules/autok3s.sh, pkg/cluster/base.go, pkg/common/common.go
- change deploy add-on manifests to autok3s folder
- If the cloud provider can't get the instance properly, the cluster item will skip the list. Add unknown status for these kinds of clusters.
=> change deploy add-on manifests folder and add unknown cluster status

hack/lib/dapper.sh, pkg/cluster/base.go
https://github.com/cnrancher/autok3s/issues/648
The defer function can't catch the error correctly because the `err` is a new variable when calling Join node function. When the error occurs, the defer error function can't refresh the cluster status.
Change to use the consistent `err` variables to ensure the error can be handled by the defer function. 
- Validate for `native` provider by creating cluster and join nodes cases. Check the cluster status can be refreshed correctly no matter success or fail.
=> fix(cluster): fix stuck in Upgrading status when join nodes failed

pkg/cluster/base.go, pkg/cluster/commands.go, pkg/types/autok3s.go
https://github.com/cnrancher/autok3s/issues/638
Support setting `INSTALL_*` environment variables defined in the K3s install script.
If users want to add environment variables for the K3s server or agent. We recommend using configuration file args. The configuration file args will be supported later.
=> feat(cluster): support setting install environment
